[build]
  publish = "_site"
  command = "bundle exec jekyll build"

[build.environment]
  RUBY_VERSION = "2.7.8"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
